tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    command: |
      cd /workspace
      if ! command -v aws &> /dev/null
      then
          if [ -f awscliv2.zip ]
          then
              echo "AWS CLI installation package already downloaded."
          else
              echo "AWS CLI is not installed and the installation package is not found. Downloading it now..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          fi
          echo "Installing AWS CLI..."
          unzip awscliv2.zip
          sudo ./aws/install
          rm -rf awscliv2.zip aws
          echo "AWS CLI installation complete."

      else
          echo "AWS CLI is already installed."
      fi
  - name: postgres
    command: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds/update-sg-rule"
  - name: react-js
    command: |
      cd frontend-react-js
      npm i
  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt
  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb  
      cd backend-flask
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - mtxr.sqltools

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public