tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      if ! command -v aws &> /dev/null
      then
          if [ -f awscliv2.zip ]
          then
              echo "AWS CLI installation package already downloaded."
          else
              echo "AWS CLI is not installed and the installation package is not found. Downloading it now..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          fi
          echo "Installing AWS CLI..."
          unzip awscliv2.zip
          sudo ./aws/install
          rm -rf awscliv2.zip aws
          echo "AWS CLI installation complete."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

      else
          echo "AWS CLI is already installed."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      fi
  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
  - name: react-js
    command: |
      cd frontend-react-js
      npm i
  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt
  - name: fargate
    before: |
      cd workspace
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      rm session-manager-plugin.deb
      cd $THEIA_WORKSPACE_ROOT
      cd backend-flask
  - name: cdk
    command: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      cp .env.example .env
      npm i
  - name: generate envs
    before: |
      source  "$THEIA_WORKSPACE_ROOT/bin/backend/generate-env"
      source  "$THEIA_WORKSPACE_ROOT/bin/frontend/generate-env"
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - mtxr.sqltools

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public