tasks:
  - init: yarn install
    command: echo "Done."
  - name: AWS CLI install
    command: cd /workspace \
            && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
            && unzip awscliv2.zip \
            && sudo /workspace/aws/install

  - name: npm
    command: cd frontend-react-js && npm i

vscode:
  extensions:
    - 42Crunch.vscode-openapi

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
